import { Grid } from '@mui/material';
import React from 'react';
import SkillItem from './SkillItem';

const SkillPanel = () => {
  return (
    <Grid
      container
      sx={{ height: '100vh' }}
      spacing={3}
      justifyContent="space-around"
      alignItems="center"
    >
      <SkillItem
        image={
          'https://cdn2.iconfinder.com/data/icons/designer-skills/128/code-programming-html-markup-develop-layout-language-256.png'
        }
        skillName={'HTML'}
        rating={4}
      />
      <SkillItem
        image={
          'https://cdn2.iconfinder.com/data/icons/designer-skills/128/code-programming-css-style-develop-layout-language-256.png'
        }
        skillName={'CSS'}
        rating={4}
      />
      <SkillItem
        image={
          'https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/187_Js_logo_logos-256.png'
        }
        skillName={'JS'}
        rating={4}
      />
      <SkillItem
        image={
          'https://cdn2.iconfinder.com/data/icons/designer-skills/128/code-programming-php-software-develop-command-language-256.png'
        }
        skillName={'PHP'}
        rating={4}
      />
      <SkillItem
        image={
          'https://cdn4.iconfinder.com/data/icons/logos-3/600/React.js_logo-512.png'
        }
        skillName={'React'}
        rating={3.5}
      />
      <SkillItem
        image={
          'https://cdn4.iconfinder.com/data/icons/logos-3/181/MySQL-256.png'
        }
        skillName={'MYSQL'}
        rating={3.0}
      />
      <SkillItem
        image={'https://images.tute.io/tute/topic/material-ui.png'}
        skillName={'MUI'}
        rating={3.0}
      />
      <SkillItem
        image={
          'https://seeklogo.com/images/N/npm-logo-01B8642EDD-seeklogo.com.png'
        }
        skillName={'NPM'}
        rating={2.5}
      />
      <SkillItem
        image={'https://iconape.com/wp-content/png_logo_vector/yarn-logo.png'}
        skillName={'Yarn'}
        rating={2.5}
      />
      <SkillItem
        image={
          'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Laravel.svg/1200px-Laravel.svg.png'
        }
        skillName={'Laravel'}
        rating={0.5}
      />
      <SkillItem
        image={
          'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/.NET_Core_Logo.svg/2048px-.NET_Core_Logo.svg.png'
        }
        skillName={'ASP.Net Core'}
        rating={0.5}
      />
      <SkillItem
        image={
          'https://www.thinksys.com/assets/images/technology/ExpressJS.png'
        }
        skillName={'ExpressJS'}
        rating={0.5}
      />
      <SkillItem
        image={
          'https://cdn0.iconfinder.com/data/icons/designer-skills/128/node-js-256.png'
        }
        skillName={'NodeJS'}
        rating={0.5}
      />
      <SkillItem
        image={
          'https://cdn4.iconfinder.com/data/icons/logos-3/512/mongodb-2-256.png'
        }
        skillName={'MongoDB'}
        rating={0.5}
      />
      <SkillItem
        image={'https://i.redd.it/tu3gt6ysfxq71.png'}
        skillName={'Unity'}
        rating={3.0}
      />
      <SkillItem
        image={
          'https://upload.wikimedia.org/wikipedia/commons/4/4f/Csharp_Logo.png'
        }
        skillName={'C#'}
        rating={3.0}
      />
    </Grid>
  );
};

export default SkillPanel;
